/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signout` | `/signout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/edit-profile` | `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/payment-methods` | `/payment-methods`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/signout` | `/signout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/activity` | `/activity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/edit-profile` | `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/payment-methods` | `/payment-methods`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/wallet` | `/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/signout${`?${string}` | `#${string}` | ''}` | `/signout${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/activity${`?${string}` | `#${string}` | ''}` | `/activity${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/edit-profile${`?${string}` | `#${string}` | ''}` | `/edit-profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/payment-methods${`?${string}` | `#${string}` | ''}` | `/payment-methods${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/wallet${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signout` | `/signout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/edit-profile` | `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/payment-methods` | `/payment-methods`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
